name: Release Build
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create release?"
        type: boolean
        required: true
        default: true

jobs:
  build:
    strategy:
      matrix:
        variant:
          - { name: "VNL", KSU: false, SUSFS: false }
          - { name: "KSU", KSU: true, SUSFS: false }
          - { name: "KSU-SUSFS", KSU: true, SUSFS: true }
    name: Build ${{ matrix.variant.name }} variant
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      KSU: ${{ matrix.variant.KSU }}
      SUSFS: ${{ matrix.variant.SUSFS }}

  release:
    name: Create Release
    needs: build
    if: ${{ github.event.inputs.create_release == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 1

      - name: Download All Artifacts
        uses: actions/download-artifact@v7
        with:
          path: release_files

      - name: Import build configs
        run: |
          source "$GITHUB_WORKSPACE/config.sh"
          {
            echo "KERNEL_NAME=$KERNEL_NAME"
            echo "RELEASE_REPO=$RELEASE_REPO"
            echo "RELEASE_BRANCH=$RELEASE_BRANCH"
          } >> "$GITHUB_ENV"

      - name: Generate new tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          RELEASE_REPO: ${{ env.RELEASE_REPO }}
        run: |
          TAG_PY="$GITHUB_WORKSPACE/py/tag.py"

          RELEASE_TAG=$(python3 "$TAG_PY" "$RELEASE_REPO")

          echo "New tag: $RELEASE_TAG"
          echo "RELEASE_TAG=$RELEASE_TAG" >> "$GITHUB_ENV"

      - name: Upload builds to release
        uses: softprops/action-gh-release@v2.5.0
        with:
          repository: ${{ env.RELEASE_REPO }}
          name: "Generic ESK Kernel ${{ env.RELEASE_TAG }}"
          tag_name: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GH_TOKEN }}
          body: |
            ### Key Changes

            - Add your key changes here.

            ---

            ### Variants Suffixes

            | Suffix | Description |
            |--------|-------------|
            | **-VNL** | No KernelSU |
            | **-KSU** | KernelSU |
            | **-SUSFS** | SUSFS Support |

            > [!IMPORTANT]
            > For installation instructions and issue reporting guidelines, please refer to the README.md
          generate_release_notes: false
          prerelease: true
          target_commitish: ${{ env.RELEASE_BRANCH }}
          files: release_files/**/*
